# Generated by Django 5.1.6 on 2025-03-03 09:41

import apps.task.models
import django.db.models.deletion
import mdeditor.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition', '0001_initial'),
        ('review', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('in_competition_position', models.PositiveSmallIntegerField(verbose_name='позиция в соревновании')),
                ('title', models.CharField(max_length=50, verbose_name='заголовок')),
                ('description', mdeditor.fields.MDTextField(verbose_name='описание')),
                ('max_attempts', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='максимальное кол-во попыток')),
                ('type', models.CharField(choices=[('input', 'Ввод правильного ответа'), ('checker', 'Ввод кода'), ('review', 'Ручная')], max_length=8, verbose_name='тип проверки')),
                ('correct_answer_file', models.FileField(blank=True, help_text='Имеет смысл только при автоматической (ввод ответа или кода) проверке.', null=True, upload_to=apps.task.models.CompetitionTask.answer_file_upload_to, verbose_name='файл с правильным ответом')),
                ('points', models.IntegerField(blank=True, null=True, verbose_name='общий балл за задание')),
                ('answer_file_path', models.TextField(blank=True, default='stdout', help_text='Путь до файла в котором ожидается результат. Пример: stdout или ./output.txt. Имеет смысл только при автоматическом типе проверки.', null=True, verbose_name='куда сделать вывод программы участнику')),
                ('submission_reviewers_count', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='кол-во проверяющих для зачета задачи')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.competition', verbose_name='привязанное соревнование')),
                ('reviewers', models.ManyToManyField(blank=True, help_text='Справа отображаются действующие проверяющие, слева - доступные для выбора. Для перемещения можно кликнуть 2 раза по проверяющему. Имеет смысл только при ручном типе проверки.', to='review.reviewer', verbose_name='ревьюверы')),
            ],
            options={
                'verbose_name': 'задание',
                'verbose_name_plural': 'задания',
            },
        ),
        migrations.CreateModel(
            name='CompetitionTaskAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.task.models.CompetitionTaskAttachment.file_upload_at, verbose_name='файл')),
                ('bind_at', models.CharField(max_length=255, verbose_name='путь сохранения')),
                ('public', models.BooleanField(default=False, verbose_name='публичный')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.competitiontask', verbose_name='задание')),
            ],
            options={
                'verbose_name': 'вложение',
                'verbose_name_plural': 'вложения',
            },
        ),
        migrations.CreateModel(
            name='CompetitionTaskCriteria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='название')),
                ('slug', models.SlugField(verbose_name='техническое название')),
                ('description', models.TextField(verbose_name='описание критерии')),
                ('max_value', models.PositiveSmallIntegerField(verbose_name='максимальное кол-во баллов')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteries', to='task.competitiontask')),
            ],
            options={
                'verbose_name': 'критерий',
                'verbose_name_plural': 'критерии',
            },
        ),
        migrations.CreateModel(
            name='CompetitionTaskSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('sent', 'Отправлено на проверку'), ('checking', 'Проверка'), ('checked', 'Проверено')], default='sent', max_length=8, verbose_name='статус')),
                ('content', models.FileField(upload_to=apps.task.models.CompetitionTaskSubmission.submission_content_upload_to, verbose_name='содержание посылки')),
                ('stdout', models.FileField(blank=True, help_text='Используется только при проверке чекером', null=True, upload_to=apps.task.models.CompetitionTaskSubmission.submission_stdout_upload_to, verbose_name='вывод программы')),
                ('result', models.JSONField(blank=True, default=None, null=True, verbose_name='результат проверки')),
                ('earned_points', models.IntegerField(blank=True, null=True, verbose_name='баллы за задание')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='дата проверки')),
                ('plagiarism_checked', models.BooleanField(default=False, verbose_name='проверено на плагиат')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='дата отправки')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.competitiontask', verbose_name='задание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'посылка',
                'verbose_name_plural': 'посылки',
            },
        ),
    ]
