# Generated by Django 5.1.6 on 2025-03-01 12:21

import apps.task.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_competition_tasks_alter_competition_participants_and_more'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitiontask',
            options={'verbose_name': 'задание', 'verbose_name_plural': 'задания'},
        ),
        migrations.AlterField(
            model_name='competitiontask',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.competition', verbose_name='соревнование'),
        ),
        migrations.AlterField(
            model_name='competitiontask',
            name='correct_answer_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.task.models.CompetitionTask.answer_file_upload_to, verbose_name='правильный ответ'),
        ),
        migrations.AlterField(
            model_name='competitiontask',
            name='criteries',
            field=models.JSONField(blank=True, null=True, verbose_name='критерии проверки'),
        ),
        migrations.AlterField(
            model_name='competitiontask',
            name='points',
            field=models.IntegerField(blank=True, null=True, verbose_name='баллы за задание'),
        ),
        migrations.AlterField(
            model_name='competitiontask',
            name='type',
            field=models.CharField(choices=[('input', 'Input'), ('checker', 'Checker'), ('review', 'Review')], max_length=8, verbose_name='тип задания'),
        ),
    ]
