# Generated by Django 5.1.6 on 2025-03-02 12:09

import apps.task.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_initial'),
        ('task', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitiontasksubmission',
            options={'verbose_name': 'посылка', 'verbose_name_plural': 'посылки'},
        ),
        migrations.AlterField(
            model_name='competitiontask',
            name='reviewers',
            field=models.ManyToManyField(blank=True, help_text='Справа отображаются действующие проверяющие, слева - доступные для выбора. Для перемещения можно кликнуть 2 раза по проверяющему', to='review.reviewer', verbose_name='ревьюверы'),
        ),
        migrations.AlterField(
            model_name='competitiontasksubmission',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата проверки'),
        ),
        migrations.AlterField(
            model_name='competitiontasksubmission',
            name='content',
            field=models.FileField(upload_to=apps.task.models.CompetitionTaskSubmission.submission_content_upload_to, verbose_name='содержание посылки'),
        ),
        migrations.AlterField(
            model_name='competitiontasksubmission',
            name='earned_points',
            field=models.IntegerField(blank=True, null=True, verbose_name='баллы за задание'),
        ),
        migrations.AlterField(
            model_name='competitiontasksubmission',
            name='plagiarism_checked',
            field=models.BooleanField(default=False, verbose_name='проверено на плагиат'),
        ),
        migrations.AlterField(
            model_name='competitiontasksubmission',
            name='result',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='результат проверки'),
        ),
        migrations.AlterField(
            model_name='competitiontasksubmission',
            name='stdout',
            field=models.FileField(blank=True, help_text='Используется только при проверке чекером', null=True, upload_to=apps.task.models.CompetitionTaskSubmission.submission_stdout_upload_to, verbose_name='вывод программы'),
        ),
        migrations.AlterField(
            model_name='competitiontasksubmission',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.competitiontask', verbose_name='задание'),
        ),
        migrations.AlterField(
            model_name='competitiontasksubmission',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата отправки'),
        ),
        migrations.AlterField(
            model_name='competitiontasksubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='пользователь'),
        ),
    ]
