# Generated by Django 5.1.6 on 2025-03-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiontask',
            name='reviewers',
            field=models.ManyToManyField(blank=True, to='review.reviewer'),
        ),
    ]
