# Generated by Django 5.1.6 on 2025-03-02 08:50

import apps.task.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiontask',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='tasks_attachments', to='task.competitiontaskattachment'),
        ),
        migrations.AlterField(
            model_name='competitiontaskattachment',
            name='bind_at',
            field=models.FilePathField(verbose_name='путь сохранения'),
        ),
        migrations.AlterField(
            model_name='competitiontaskattachment',
            name='file',
            field=models.FileField(upload_to=apps.task.models.CompetitionTaskAttachment.file_upload_at, verbose_name='файл'),
        ),
        migrations.AlterField(
            model_name='competitiontaskattachment',
            name='public',
            field=models.BooleanField(default=False, verbose_name='публичный'),
        ),
        migrations.AlterField(
            model_name='competitiontaskattachment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.competitiontask', verbose_name='задание'),
        ),
    ]
