# Generated by Django 5.1.6 on 2025-03-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competetiontasksumbission',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='reviewers', to='review.reviewer'),
        ),
    ]
