# Generated by Django 5.1.6 on 2025-03-01 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitiontask',
            options={'verbose_name': 'задание', 'verbose_name_plural': 'задания'},
        ),
    ]
