# Generated by Django 5.1.6 on 2025-03-02 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_competitiontask_attachments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitiontask',
            name='attachments',
        ),
    ]
