# Generated by Django 5.1.6 on 2025-03-01 13:49

import apps.task.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_remove_competition_tasks'),
        ('task', '0002_alter_competitiontask_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiontask',
            name='max_attemps',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='competitiontask',
            name='answer_file_path',
            field=models.TextField(blank=True, default='stdout', null=True, verbose_name='куда сохранять решения'),
        ),
        migrations.AlterField(
            model_name='competitiontask',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.competition'),
        ),
        migrations.AlterField(
            model_name='competitiontask',
            name='correct_answer_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.task.models.CompetitionTask.answer_file_upload_to, verbose_name='файл с правильным ответом'),
        ),
        migrations.AlterField(
            model_name='competitiontask',
            name='criteries',
            field=models.JSONField(blank=True, null=True, verbose_name='критерии'),
        ),
        migrations.AlterField(
            model_name='competitiontask',
            name='title',
            field=models.CharField(max_length=50, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='competitiontask',
            name='type',
            field=models.CharField(choices=[('input', 'Ввод правильного ответа'), ('checker', 'Вывод кода'), ('review', 'Ручная')], max_length=8, verbose_name='тип проверки'),
        ),
    ]
