# Generated by Django 5.1.6 on 2025-03-02 12:23

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_competitiontasksubmission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitiontask',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='описание'),
        ),
    ]
