# Generated by Django 5.1.6 on 2025-03-03 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_competitiontasksubmission_plagiarism_checked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitiontaskattachment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='task.competitiontask', verbose_name='задание'),
        ),
    ]
