# Generated by Django 5.1.6 on 2025-03-02 12:49

import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_competitiontask_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiontask',
            name='submission_reviewers_count',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='competitiontask',
            name='description',
            field=martor.models.MartorField(verbose_name='описание'),
        ),
    ]
