# Generated by Django 5.1.6 on 2025-03-01 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_competetiontasksumbission_reviewers'),
        ('task', '0003_competitiontask_max_attemps_and_more'),
    ]

    operations = [
    ]
