# Generated by Django 5.1.6 on 2025-03-03 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_competitiontaskattachment_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitiontaskattachment',
            name='bind_at',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^(?:[a-zA-Z]:\\\\(?:[^<>:\\"\\/\\\\|?*]*\\\\)*|/(?:[^<>:\\"\\/\\\\|?*]+/?)*)$', message='Введите абсолютный путь до папки')], verbose_name='путь сохранения'),
        ),
    ]
