# Generated by Django 5.1.6 on 2025-03-01 14:47

import apps.task.models
import django.db.models.deletion
import tinymce.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_merge_20250301_1739'),
        ('user', '0002_alter_user_email_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitiontask',
            name='description',
            field=tinymce.models.HTMLField(max_length=300, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='competitiontask',
            name='max_attemps',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.CreateModel(
            name='CompetitionTaskSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('checking', 'Checking'), ('checked', 'Checked')], default='sent', max_length=8)),
                ('content', models.FileField(upload_to=apps.task.models.CompetitionTaskSubmission.submission_content_upload_to)),
                ('stdout', models.FileField(blank=True, null=True, upload_to=apps.task.models.CompetitionTaskSubmission.submission_stdout_upload_to)),
                ('result', models.JSONField(blank=True, default=None, null=True)),
                ('earned_points', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.competitiontask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CompetetionTaskSumbission',
        ),
    ]
