# Generated by Django 5.1.6 on 2025-03-01 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review'),
        ('task', '0005_alter_competitiontask_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.competitiontasksubmission'),
        ),
    ]
