# Generated by Django 5.1.6 on 2025-03-02 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_initial'),
        ('task', '0002_competitiontask_attachments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'проверка', 'verbose_name_plural': 'проверки'},
        ),
        migrations.AlterModelOptions(
            name='reviewer',
            options={'verbose_name': 'проверяющий', 'verbose_name_plural': 'проверяющие'},
        ),
        migrations.AlterField(
            model_name='review',
            name='evaluation',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='выполнение'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.reviewer', verbose_name='проверяющий'),
        ),
        migrations.AlterField(
            model_name='review',
            name='state',
            field=models.CharField(choices=[('not_checked', 'Not Checked'), ('checking', 'Checking'), ('checked', 'Checked')], default='not_checked', max_length=11, verbose_name='состояние'),
        ),
        migrations.AlterField(
            model_name='review',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='task.competitiontasksubmission', verbose_name='посылка'),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='token',
            field=models.CharField(max_length=100, verbose_name='токен для входа'),
        ),
    ]
