apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    orgId: 1
    uid: prometheus
    isDefault: false
    editable: false
  - name: Infinity
    type: yesoreyeram-infinity-datasource
    access: proxy
    orgId: 1
    uid: infinity
    isDefault: false
    editable: false
