# Generated by Django 5.1.6 on 2025-02-28 21:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image_url', models.FileField(blank=True, null=True, upload_to='', verbose_name='Изображение соревнования')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн участия')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн участия')),
                ('type', models.CharField(choices=[('solo', 'Solo')], max_length=10, verbose_name='Тип участия')),
                ('participation_type', models.CharField(choices=[('edu', 'Edu'), ('competitive', 'Competitive')], max_length=11, verbose_name='Тип соревнования')),
            ],
            options={
                'verbose_name': 'соревнование',
                'verbose_name_plural': 'соревнования',
            },
        ),
    ]
