# Generated by Django 5.1.6 on 2025-03-01 08:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image_url', models.FileField(blank=True, null=True, upload_to='', verbose_name='Изображение соревнования')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн участия')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн участия')),
                ('type', models.CharField(choices=[('solo', 'Solo')], max_length=10, verbose_name='Тип участия')),
                ('participation_type', models.CharField(choices=[('edu', 'Edu'), ('competitive', 'Competitive')], max_length=11, verbose_name='Тип соревнования')),
                ('participants', models.ManyToManyField(related_name='participants', to='user.user')),
            ],
            options={
                'verbose_name': 'соревнование',
                'verbose_name_plural': 'соревнования',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('not_started', 'Not Started'), ('started', 'Started'), ('finished', 'Finished')], max_length=11)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
