# Generated by Django 5.1.6 on 2025-03-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
        ('task', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='task.competitiontask'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='participants',
            field=models.ManyToManyField(blank=True, editable=False, related_name='participants', to='user.user'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='participation_type',
            field=models.CharField(choices=[('edu', 'Образовательный'), ('competitive', 'Соревновательный')], max_length=11, verbose_name='Тип соревнования'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='type',
            field=models.CharField(choices=[('solo', 'Индивидуальный')], max_length=10, verbose_name='Тип участия'),
        ),
    ]
