# Generated by Django 5.2 on 2025-04-07 21:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'участие', 'verbose_name_plural': 'участия'},
        ),
        migrations.AlterField(
            model_name='state',
            name='changed_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='изменено'),
        ),
        migrations.AlterField(
            model_name='state',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.competition', verbose_name='соревнование'),
        ),
        migrations.AlterField(
            model_name='state',
            name='state',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('started', 'Started'), ('finished', 'Finished')], default='not_started', max_length=11, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='state',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='участник'),
        ),
    ]
