# Generated by Django 5.1.6 on 2025-02-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
        ('user', '0002_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to='user.user'),
        ),
    ]
