# Generated by Django 5.1.6 on 2025-03-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_competition_tasks_alter_competition_participants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='tasks',
        ),
    ]
