# Generated by Django 5.1.6 on 2025-03-01 14:46

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_remove_competition_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дедлайн участия'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='image_url',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='изображение соревнования'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='participation_type',
            field=models.CharField(choices=[('edu', 'Образовательный'), ('competitive', 'Соревновательный')], max_length=11, verbose_name='тип соревнования'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дедлайн участия'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='title',
            field=models.CharField(max_length=100, verbose_name='аазвание'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='type',
            field=models.CharField(choices=[('solo', 'Индивидуальный')], max_length=10, verbose_name='тип участия'),
        ),
    ]
