# Generated by Django 5.1.6 on 2025-03-01 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='changed_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
