# Global config
global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10m
  external_labels:
    environment: local
    instance: somemachinelol

scrape_configs:
  # Prometheus
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  # Postgres
  - job_name: postgres
    scrape_interval: 10s
    static_configs:
      - targets: ["postgres-exporter:9187"]

  # Redis
  - job_name: redis
    scrape_interval: 10s
    static_configs:
      - targets: ["redis-exporter:9121"]

  # Celery
  - job_name: celery
    scrape_interval: 30s
    static_configs:
      - targets: ["celery-exporter:9808"]
