#!/bin/sh

python manage.py migrate
if [ $? -ne 0 ]; then
    echo "Migration failed"
    exit 1
fi

if [ "$DJANGO_CREATE_SUPERUSER" = "True" ]; then
    python manage.py createsuperuser --noinput --username "$DJANGO_SUPERUSER_USERNAME" --email "$DJANGO_SUPERUSER_EMAIL" || true
fi
