FROM docker.io/python:3.13-slim

ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY checker_requirements.txt .

RUN pip install --no-cache-dir -r checker_requirements.txt

CMD ["sleep", "infinity"]
