[project]
name = "checker"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.11.13",
    "docker>=7.1.0",
    "fastapi>=0.115.11",
    "python-multipart>=0.0.20",
    "regex>=2024.11.6",
    "uvicorn>=0.34.0",
]
