# Generated by Django 5.1.6 on 2025-03-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(verbose_name='пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.SlugField(unique=True, verbose_name='юзернейм'),
        ),
    ]
