# Generated by Django 5.1.6 on 2025-03-02 12:09

import apps.achievement.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('icon', models.FileField(upload_to=apps.achievement.models.Achievement.image_url_upload_to, verbose_name='иконка достижения')),
            ],
            options={
                'verbose_name': 'ачивка',
                'verbose_name_plural': 'ачивки',
            },
        ),
    ]
