# Generated by Django 5.1.6 on 2025-03-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('achievement', '0003_remove_achievement_need_count_and_more'), ('achievement', '0004_alter_achievement_slug')]

    dependencies = [
        ('achievement', '0002_achievement_need_count_achievement_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='need_count',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='type',
        ),
        migrations.AddField(
            model_name='achievement',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='слаг'),
        ),
    ]
