# Generated by Django 5.2 on 2025-04-07 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userachievement',
            options={'verbose_name': 'выданная ачивка', 'verbose_name_plural': 'выданные ачивки'},
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievement.achievement', verbose_name='ачивка'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата получения'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='пользователь'),
        ),
    ]
