# Generated by Django 5.1.6 on 2025-03-02 14:03

import apps.achievement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0003_remove_achievement_need_count_and_more_squashed_0004_alter_achievement_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.ImageField(upload_to=apps.achievement.models.Achievement.image_url_upload_to, verbose_name='иконка достижения'),
        ),
    ]
